-- Знайти оцінки студентів у окремій групі з певного предмета
-- 1) Run the following script in SQL console for test database OR
-- 2) Copy-Paste the following script in "select.py" after "sql_expression_from_query = """
